### PR TITLE
getLaunchMode should return 'NEW_WINDOW' if _activeOnSelector is blank

### LINKED ISSUE #11: extension doesn't work if _activeOnSelector is not set
Using the following configuration:

```json
"_launchNewWindow": {
    "_isEnabled": true,
    "_stopSessionInitialize": true,
    "_activeOnPages": [
        "index.html"
    ],
    "_activeOnSelector": "",
    "_target": "courseWin",
    "_strWindowFeatures": "width={{width}},height={{height}},menubar=no,location=no,directories=no,resizable=yes,scrollbars=yes",
    "_delay": 500,
    "preLaunchTitle": "The course should now open in a new browser window.",
    "preLaunchBody": "If this does not occur, please deactivate any popup blocking software - then <a href=\"{{href}}\" target=\"_blank\">click here</a> or refresh this page to try again.",
    "launchTitle": "The course should now be open in a new browser window.",
    "launchBody": "Please ensure you don't close or do anything in this window whilst the course is in progress.",
    "closedTitle": "You have closed the course.",
    "closedBody": "Please close this window to continue."
}
```

I'd expect the extension to launch the course in a new window any time it's run from index.html; instead it never does.

If you set `_activeOnSelector` to a class that's guaranteed to be found on the `html` element - e.g. `".js"`, it works fine.

### PR DESCRIPTION
**Pull request by moloko**
fixes #11

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

File: js/adapt-launchNewWindow.js [hunk 1]
```diff
@@ -1,225 +1,225 @@
...
-            var $html = $("html");
-            var isNewWindow = this._config._activeOnSelector && $html.is(this._config._activeOnSelector);
-            
-            if (isNewWindow) return LAUNCH_MODE.NEW_WINDOW;
+    getLaunchMode: function() {
+      if (!this._config._activeOnSelector) return LAUNCH_MODE.NEW_WINDOW;
 
-            return LAUNCH_MODE.CURRENT_WINDOW;
+      var $html = $('html');
+      var isNewWindow = this._config._activeOnSelector && $html.is(this._config._activeOnSelector);
```
Comment (tomgreenfield) [inline js/adapt-launchNewWindow.js]: `this._config._activeOnSelector` will _always_ be truthy here with the new line 87.

Logic could simply be:
```js
var selector = this._config._activeOnSelector;
var isNewWindow = !selector || $('html').is(selector);
```
(no idea why `$html` was cached).

Comment (moloko) [reply js/adapt-launchNewWindow.js]: good call. and with this style I think `isNewWindow` is pretty redundant, the name of the ENUM makes it pretty clear what's going on.

**Review by tomgreenfield — APPROVED** [review]
:eye:
